---
- name: Deploy Autofs Clients
  hosts: clients
  become: yes
  vars:
    # --- OS setup ---
    # Shouldn't need to modify
    autofs_pkgs:
      Linux: [ 'autofs' ]
      Darwin: []

    # --- OS config ---
    # Shouldn't need to modify
    autofs_master:
      Linux: "/etc/auto.master"
      Darwin: "/etc/auto_master"

    autofs_indirect_maps:
      - name: "auto.nfs-nas"
        path: "/mnt/nfs"
        mark: "nfs mounts from NAS"
        options: "--timeout=30 --ghost"
        mounts:
          - name: "fighters1"
            fstype: "nfs,rw,bg,hard,intr,tcp,resvport"
            url: "192.168.60.5:/cephfs/ezbld"
          - name: "fighters2"
            fstype: "nfs,rw,bg,hard,intr,tcp,resvport"
            url: "192.168.60.5:/cephfs/iRod_Test"
          - name: "fighters3"
            fstype: "nfs,rw,bg,hard,intr,tcp,resvport"
            url: "192.168.60.5:/cephfs/Repo_Temp"
          - name: "fighters4"
            fstype: "nfs,rw,bg,hard,intr,tcp,resvport"
            url: "192.168.60.5:/cephfs/users"
  pre_tasks:

     #change vagrant group, conflicts with slurm
    - name: "Change Centos & Vagrant User Group ID"
      group:
        name: "{{ item.group }}"
        gid: "{{ item.gid }}"
        state: present
      with_items:
        - { gid: 9500, group: centos }
        - { gid: 9600, group: vagrant }

  handlers:
    - import_tasks: handlers/main.yml
  tasks:

    - import_tasks: "tasks/main.yml"

    - name: Reboot Node
      reboot:
        reboot_timeout: 3600
